name: cinedreams
favicon: null
layout_spectrum: 0.8933626250363886
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#182c38'
    - '#4f7783'
    - '#bfb89e'
    - '#050406'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
